Models/ErrorViewModel.cs
namespace segundapractica.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace segundapractica.Models
{
    [Table("t_registro")]
    public class UsuarioModel
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        public string? NombreCompleto { get; set; }
        public string? ApellidoPaterno { get; set; }
        public string? ApellidoMaterno { get; set; }
        public string? TipoDocumento { get; set; }
        public string? Telefono { get; set; }
        public string? Genero { get; set; }
        public string? CorreoElectronico { get; set; }
        public string? TipoCuenta { get; set; }
        public string? Pais { get; set; }
        public decimal SaldoInicial { get; set; }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using segundapractica.Models;

namespace segundapractica.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using segundapractica.Data;
using segundapractica.Models;

namespace segundapractica.Controllers
{
    public class RegistroController : Controller
    {
        private readonly ILogger<RegistroController> _logger;
        private readonly ApplicationDbContext _context;

        public RegistroController(ILogger<RegistroController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Abrir(UsuarioModel usuario)
        {
            _context.Add(usuario);
            _context.SaveChanges();
            ViewData["Message"] = "Se Abrio tu cuenta Bancaria";
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Registro/Index.cshtml
@model segundapractica.Models.UsuarioModel;

@{
    ViewData["Title"] = "Abrir Cuenta";
}

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">Abrir cuenta Bancaria en el Banco EE.UU.</h3>
        </div>
        <div class="card-body">
            <form asp-controller="Registro" asp-action="Abrir" method="post">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Datos Personales</h4>
                        <div class="mb-3">
                            <label asp-for="NombreCompleto" class="form-label">Nombre Completo</label>
                            <input asp-for="NombreCompleto" type="text" class="form-control"
                                placeholder="Ingresa tu nombre completo" required>
                        </div>
                        <div class="mb-3">
                            <label asp-for="ApellidoPaterno" class="form-label">Apellido Paterno</label>
                            <input asp-for="ApellidoPaterno" type="text" class="form-control"
                                placeholder="Ingresa tu apellido paterno" required>
                        </div>
                        <div class="mb-3">
                            <label asp-for="ApellidoMaterno" class="form-label">Apellido Materno</label>
                            <input asp-for="ApellidoMaterno" type="text" class="form-control"
                                placeholder="Ingresa tu apellido materno" required>
                        </div>
                        <div class="mb-3">
                            <label asp-for="TipoDocumento" class="form-label">Tipo de Documento</label>
                            <select asp-for="TipoDocumento" class="form-select" id="tipo_documento" required>
                                <option selected disabled value="">Selecciona el tipo de documento</option>
                                <option value="dni">DNI</option>
                                <option value="ruc">RUC</option>
                                <option value="pasaporte">Pasaporte</option>
                                <option value="carnet_extranjeria">Carnet de Extranjería</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Telefono" class="form-label">Teléfono</label>
                            <input asp-for="Telefono" type="tel" class="form-control"
                                placeholder="Ingresa tu número de teléfono" required>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Genero" class="form-label">Tipo de Género</label>
                            <select asp-for="Genero" class="form-select" id="tipo_documento" required>
                                <option selected disabled value="">Selecciona el tipo de género</option>
                                <option value="masculino">Masculino</option>
                                <option value="femenino">Femenino</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <h4>Información para la Cuenta</h4>
                        <div class="mb-3">
                            <label asp-for="CorreoElectronico" class="form-label">Correo Electrónico</label>
                            <input asp-for="CorreoElectronico" type="email" class="form-control"
                                placeholder="Ingresa tu correo electrónico" required>
                        </div>
                        <div class="mb-3">
                            <label asp-for="TipoCuenta" class="form-label">Tipo de Cuenta</label>
                            <select asp-for="TipoCuenta" class="form-select" id="tipo_cuenta" required>
                                <option selected disabled value="">Selecciona el tipo de cuenta</option>
                                <option value="personal">Cuenta Personal</option>
                                <option value="empresarial">Cuenta Empresarial</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Pais" class="form-label">Ingresa tu País</label>
                            <input asp-for="Pais" type="text" class="form-control"
                                placeholder="Ingresa tu país de nacimiento" required>
                        </div>
                        <div class="mb-3">
                            <label asp-for="SaldoInicial" class="form-label">Ingresa tu Saldo Inicial</label>
                            <input asp-for="SaldoInicial" type="text" class="form-control" min="0"
                                placeholder="Ingresa tu Saldo inicial" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Contraseña</label>
                            <input type="password" class="form-control" placeholder="Ingresa tu contraseña" required>
                        </div>
                    </div>
                </div>

                <div class="mt-4 text-center">
                    <button type="submit" class="btn btn-primary w-100">Enviar Formulario</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - segundapractica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/segundapractica.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">segundapractica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registro" asp-action="Index">Abrir
                                cuenta</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - segundapractica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>